### ISSUE TITLE
[DISCUSSION] Problems when runninig benchmarks with dependencies

### ISSUE THREAD

**Issue by tallysmartins** [elixir-bench/elixir-bench-runner#5]
Hi guys. I am opening this issue to discuss about the way the benchmark runs are built with docker, specially when they have dependencies, like a database or some external service. 

In the ecto repository we have a benchmark with the following `config.yml` file: 

```
elixir: 1.5.2
erlang: 20.1.2
environment:
  PG_URL: postgres:postgres@localhost
  MYSQL_URL: root@localhost
deps:
  docker:
    - container_name: postgres
      image: postgres:9.6.6-alpine
    - container_name: mysql
      image: mysql:5.7.20
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
```

The `mysql` and `postgres` dependencies are added to a docker-compose file with the runner-container image and then they are all started to run the benchmarks. The problem is that, this way we have a sync issue because docker does not give easy options to guarantee that  the database containers will start and get ready before the benchmarks start running. Reading docker docs, they suggest to write our own scripts to check for the health of a service to [control the start up process](https://docs.docker.com/compose/startup-order/). Before this, they suggest the application to check for the connection and be sensitive to lose and reconnect to it.

By now, the solutions that I have thought to better deal with this are:

### Leave the check to the application level
For instance, the Ecto code that initialize the database adapters to run the benchmarks that needs the database up could try to connect until its ready

#### Pros:
 - We don't have to worry about any service check and applications deal with it and create their own **retry/fail** logic
 - We could just worry about a max time for the job run 

#### Cons:
 - Its one more thing that applications must worry about and if they do not handle it in the best way the job run can spend the `max time` trying to connect to a service before it fails.

### Provisioning dependencies before the benchmarks run 
  We could offer a list of services that we support, the same way TravisCI does with the `addons` option in the `travis-ci.yml`. This would need changes in the parser and the way we provision this dependencies would require a specific script for each one. Also, support to different versions would be a big thing. We could just install them inside the same image of the runner to keep with the actual docker infrastructure or we could move to virtual machines. (the same way that Travis does)

#### Pros:
 -  Full control of provisioning dependencies, giving reliability to set up everything before run the benchmarks
 - We could try to get inspiration from Travis to get its scripts and how they do this. I saw that they have chef cookbooks for each service that they support.

#### Cons:
 - Big changes in the parser and the way we trigger the build
 - A little bit more complex
 - We would need to write the scripts to provision each service 

#### Observation:
 - We would need to decide if we can do the provisioning inside the same docker container without affecting too much the benchmarks, at least by now, or if its already necessary to thing about changing to virtual machines. (idk the answer, but I would try to stick with the docker in the first place although its purpose is to distribute services in multiple containers).

**Comment by PragTob** [comment]
:wave: 

Thanks for writing this up.

I think docker is perfectly suitable for what we want to do - travis also uses docker afaik unless you go onto the legacy infrastructure.

I also think it's important for us that people can specify their own docker containers - so we don't have to deal with versions and maintain those images etc.

I think an easy way out/around for now might be that we could an additional key when setting up the containers for a "ready-script" or something - a script that we'll run periodically (say every second) and once it has a non 0 exit code we consider the container (or all containers) up and operational.

We can provide examples for containers but it's extensible enough so that people can make it work with whatever.

What do you think?

Also @michalmuskala as he knows more about this than me as usual :)

**Comment by tallysmartins** [comment]
There's an easier setup I can think now which is using a shell script that test TCP connections in a specified port. The [wait-for script](https://github.com/Eficode/wait-for) is mentioned in the docker documentation. It allows the use of a command to check if the service is receiving connections. It also allows the use of timeout flags and test multiple services at once, so we could do something like:

`./wait-for.sh mysql:3306 postgres:5432 -t 100 -- mix run bench/bench_helper.exs`

And to build this command we could read a `wait-on-port` or `wait-for` option in the config.yml. First one would work by magic number set by us to check health until it times out, let's say 100 seconds, for example. Or we can allow developers to specify this parameter giving a value consistent with reality, below 5 minutes, for example.

In both cases we not necessarily need to cancel/fail the job run, they can try to proceed. This way projects can even have a check/retry logic in the application level if they need more time than the timeout period.

```
deps:
  docker:
    - container_name: postgres
      image: postgres:9.6.6-alpine
      wait-on-port: 5432
    - container_name: mysql
      image: mysql:5.7.20
      wait-for: 
         port: 3306
         timeout: 100 # in seconds, but must be less than 5 minutes
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
``` 
This covers most of what external services do, which is serve a TCP connection. There are more sophisticated wrappers that can test other types of sockets and protocols, UDP, Unix and even "files" created, but this seems to be enough now. What do you think?
